### ISSUE TITLE
Answer

### ISSUE THREAD

**Issue by rainbi48** [lloricode/ci-capstone#38]
Please, post database too..
thanks

**Comment by lloricode** [comment]
@rainbi48 just create a databse named `ci_capstone` ,then just run a system, table will auto migrate :)

if any problem just make another issue :)

btw just read README.md if any, i will update if any changes in system.

**Comment by iEdzar** [comment]
on the settings tab we have an option to back up the database. download it from our live sample 
[here](http://ci-capstone.lloricmayugagarcia.com/) and import it on your local db
