### ISSUE TITLE
Cannot enroll subject/s

### ISSUE THREAD

**Issue by iEdzar** [lloricode/ci-capstone#51]
If we add a student or a student enrolls a subject, it cannot enroll the subject. A warning is triggered as "no unit" in create-student-subject controller.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/18072918/25388256/ea2b8836-29ff-11e7-8781-7e17d2735bbe.png)

**Comment by lloricode** [comment]
resolved from [this commit](https://github.com/lloricode/ci-capstone/commit/c8a0536eccf791def5f913e62bc226ad676d6577)
