### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Karla02** [lloricode/ci-capstone#77]
When I try to run the program "http://localhost/ci-capstone" it always direct me to

"http://localhost/ci-capstone/en/auth/login" 
 
Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

**Comment by lloricode** [comment]
hmmm did you run your server or created a database before test it?

**Comment by Karla02** [comment]
Yes. My configurations are also correct but why I cant run it? :(

**Comment by lloricode** [comment]
hmm, can you give me a screen shot,
then later ill try to tun it again, because it has a long time ago since we implemented this :)

**Comment by Karla02** [comment]
![ggggggg](https://user-images.githubusercontent.com/36364592/38548436-610013ee-3ce4-11e8-8caf-982a035783f8.jpg)

Here's the my problem it always direct me here

**Comment by lloricode** [comment]
ok, is there any view redered? if not.. try to changes the folder name of
you project just like the repository name

**Comment by lloricode** [comment]
change to `ci-capstone`, or if you not want to change the folder name..
just make sure it the same as the `base_url` with the folder name

**Comment by Karla02** [comment]
![w](https://user-images.githubusercontent.com/36364592/38555244-095e4b56-3cf8-11e8-85ef-362d138999a5.jpg)

**Comment by Karla02** [comment]
I think its working now right? hahaha 
So, What is the password for admin@admin.com?

**Comment by lloricode** [comment]
Great 😊😊😊
