### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by jmnantes** [lloricode/ci-capstone#81]
![image](https://user-images.githubusercontent.com/58283800/195213319-443440c2-2a06-4834-a366-2cd70a61afcf.png)

**Comment by lloricode** [comment]
Hi, please update this configuration base on your environment set up

https://github.com/lloricode/ci-capstone/blob/c26b492400aec8a11e3868a374a4c12c181ade5b/application/config/development/database.php#L78
